# Generated by Django 4.2.16 on 2024-11-14 17:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('rel_year', models.IntegerField()),
                ('rel_decade', models.IntegerField()),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('chart_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('chart_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('scent', models.FloatField()),
                ('longevity', models.FloatField()),
                ('sillage', models.FloatField()),
                ('bottle', models.FloatField()),
                ('value_for_money', models.FloatField()),
            ],
        ),
    ]
