# Generated by Django 4.2.16 on 2024-12-13 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_backlog_perfume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='chart_categories',
            new_name='occasion',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='chart_numbers',
            new_name='occasion_numbers',
        ),
        migrations.AddField(
            model_name='perfume',
            name='season',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='perfume',
            name='season_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='perfume',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='perfume',
            name='style_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='perfume',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='perfume',
            name='type_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
