# Generated by Django 4.2.16 on 2025-01-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_rename_chart_categories_perfume_occasion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('decade', models.IntegerField()),
                ('gender', models.TextField()),
                ('curated', models.BooleanField()),
                ('cluster', models.IntegerField()),
                ('reduction', models.TextField()),
                ('clusterization', models.TextField()),
            ],
        ),
    ]
