# Generated by Django 4.2.16 on 2025-01-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='decade',
            field=models.TextField(default='All'),
        ),
    ]
