# Generated by Django 4.2.16 on 2025-01-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_alter_clusters_decade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.TextField(default='No image'),
        ),
    ]
