# Generated by Django 4.2.16 on 2025-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_perfume_description_perfume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='generated_descriptions',
            field=models.TextField(default='No description'),
        ),
    ]
