# Generated by Django 4.2.16 on 2025-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_perfume_generated_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='link',
            field=models.TextField(unique=True),
        ),
    ]
